 
 export  const QuickLinkData={
    Nagpur: [
      "Hair Transplant In Nagpur",
      "Hair Transplant Specialist In Nagpur",
      "Dermatologist In Nagpur",
      "Hair Transplant Clinic In Nagpur",
      "Best Hair Transplant Clinic In Nagpur",
      "Top Rated Hair Specialist In Nagpur",
      "Laser Hair Removal in Nagpur",
      "Tattoo Removal In Nagpur",
      "Vampire Facial In Nagpur",
      "PRP Therapy / Treatment In Nagpur",
      "Skin Specialist In Nagpur",
      "Skin Clinic In Nagpur",
      "Skin Doctor In Nagpur",
      "Hydra Facial In Nagpur",
      "Botox Treatment In Nagpur",
      "Fillers Treatment In Nagpur",
      "Carbon Peel Treatment In Nagpur",
      "Scar Removal In Nagpur",
      "Ear Piercing In Nagpur",
      "Best Skin Specialist In Nagpur",
      "Best Dermatologist In Nagpur",
      "Cosmetologist In Nagpur",
      "Best Cosmetologist In Nagpur",
      "Best Hair Transplant In Nagpur",
      "Best Hair Transplant Specialist Doctor In Nagpur"
    ],
    Katni: [
      "Hair Transplant In Katni",
      "Hair Transplant Specialist In Katni",
      "Hair Transplant Clinic In Katni",
      "Hair Transplant Doctor In Katni",
      "Top Rated Hair Transplant Specialist In Katni",
      "Top Rated Hair Transplant Doctor In Katni",
      "PRP Treatment In Katni",
      "PRP Therapy In Katni",
      "Skin Specialist In Katni",
      "Skin Doctor In Katni",
      "Skin Clinic In Katni",
      "Dermatologist In Katni",
      "Cosmetologist In Katni"
    ],
    Narsinghpur: [
      "Hair Transplant In Narsinghpur",
      "Hair Transplant Specialist In Narsinghpur",
      "Hair Transplant Clinic In Narsinghpur",
      "Hair Transplant Doctor In Narsinghpur",
      "Top Rated Hair Transplant Specialist In Narsinghpur",
      "Top Rated Hair Transplant Doctor In Narsinghpur",
      "PRP Treatment In Narsinghpur",
      "PRP Therapy In Narsinghpur",
      "Skin Specialist In Narsinghpur",
      "Skin Doctor In Narsinghpur",
      "Skin Clinic In Narsinghpur",
      "Dermatologist In Narsinghpur",
      "Cosmetologist In Narsinghpur"
    ],
    Rajangaon: [
      "Hair Transplant In Rajangaon",
      "Hair Transplant Specialist In Rajangaon",
      "Hair Transplant Clinic In Rajangaon",
      "Hair Transplant Doctor In Rajangaon",
      "Top Rated Hair Transplant Specialist In Rajangaon",
      "Top Rated Hair Transplant Doctor In Rajangaon",
      "PRP Treatment In Rajangaon",
      "PRP Therapy In Rajangaon",
      "Skin Specialist In Rajangaon",
      "Skin Doctor In Rajangaon",
      "Skin Clinic In Rajangaon",
      "Dermatologist In Rajangaon",
      "Cosmetologist In Rajangaon"
    ],
    Harda: [
      "Hair Transplant In Harda",
      "Hair Transplant Specialist In Harda",
      "Hair Transplant Clinic In Harda",
      "Hair Transplant Doctor In Harda",
      "Top Rated Hair Transplant Specialist In Harda",
      "Top Rated Hair Transplant Doctor In Harda",
      "PRP Treatment In Harda",
      "PRP Therapy In Harda",
      "Skin Specialist In Harda",
      "Skin Doctor In Harda",
      "Skin Clinic In Harda",
      "Dermatologist In Harda",
      "Cosmetologist In Harda"
    ],
    Chandrapur: [
      "Hair Transplant In Chandrapur",
      "Hair Transplant Specialist In Chandrapur",
      "Hair Transplant Clinic In Chandrapur",
      "Hair Transplant Doctor In Chandrapur",
      "Top Rated Hair Transplant Specialist In Chandrapur",
      "Top Rated Hair Transplant Doctor In Chandrapur",
      "PRP Treatment In Chandrapur",
      "PRP Therapy In Chandrapur",
      "Skin Specialist In Chandrapur",
      "Skin Doctor In Chandrapur",
      "Skin Clinic In Chandrapur",
      "Dermatologist In Chandrapur",
      "Cosmetologist In Chandrapur"
    ],
    Akola: [
      "Hair Transplant In Akola",
      "Hair Transplant Specialist In Akola",
      "Dermatologist In Akola"
    ],
    Jabalpur: [
      "Hair Transplant In Jabalpur",
      "Hair Transplant Specialist In Jabalpur",
      "Dermatologist In Jabalpur"
    ],
    Amravati: [
      "Hair Transplant In Amravati",
      "Hair Transplant Specialist In Amravati",
      "Hair Transplant Clinic In Amravati",
      "Hair Transplant Doctor In Amravati",
      "Top Rated Hair Transplant Specialist In Amravati",
      "Top Rated Hair Transplant Doctor In Amravati",
      "PRP Treatment In Amravati",
      "PRP Therapy In Amravati",
      "Skin Specialist In Amravati",
      "Skin Doctor In Amravati",
      "Skin Clinic In Amravati",
      "Dermatologist In Amravati",
      "Cosmetologist In Amravati"
    ],
    Ambikapur: [
      "Hair Transplant In Ambikapur",
      "Hair Transplant Specialist In Ambikapur",
      "Hair Transplant Clinic In Ambikapur",
      "Hair Transplant Doctor In Ambikapur",
      "Top Rated Hair Transplant Specialist In Ambikapur",
      "Top Rated Hair Transplant Doctor In Ambikapur",
      "PRP Treatment In Ambikapur",
      "PRP Therapy In Ambikapur",
      "Skin Specialist In Ambikapur",
      "Skin Doctor In Ambikapur",
      "Skin Clinic In Ambikapur",
      "Dermatologist In Ambikapur",
      "Cosmetologist In Ambikapur"
    ],
    Bhandara: [
      "Hair Transplant In Bhandara",
      "Hair Transplant Specialist In Bhandara",
      "Hair Transplant Clinic In Bhandara",
      "Hair Transplant Doctor In Bhandara",
      "Top Rated Hair Transplant Specialist In Bhandara",
      "Top Rated Hair Transplant Doctor In Bhandara",
      "PRP Treatment In Bhandara",
      "PRP Therapy In Bhandara",
      "Skin Specialist In Bhandara",
      "Skin Doctor In Bhandara",
      "Skin Clinic In Bhandara",
      "Dermatologist In Bhandara",
      "Cosmetologist In Bhandara"
    ],
    Korba: [
      "Hair Transplant In Korba",
      "Hair Transplant Specialist In Korba",
      "Hair Transplant Clinic In Korba",
      "Hair Transplant Doctor In Korba",
      "Top Rated Hair Transplant Specialist In Korba",
      "Top Rated Hair Transplant Doctor In Korba",
      "PRP Treatment In Korba",
      "PRP Therapy In Korba",
      "Skin Specialist In Korba",
      "Skin Doctor In Korba",
      "Skin Clinic In Korba",
      "Dermatologist In Korba",
      "Cosmetologist In Korba"
    ],
    Mandla: [
      "Hair Transplant In Mandla",
      "Hair Transplant Specialist In Mandla",
      "Hair Transplant Clinic In Mandla",
      "Hair Transplant Doctor In Mandla",
      "Top Rated Hair Transplant Specialist In Mandla",
      "Top Rated Hair Transplant Doctor In Mandla",
      "PRP Treatment In Mandla",
      "PRP Therapy In Mandla",
      "Skin Specialist In Mandla",
      "Skin Doctor In Mandla",
      "Skin Clinic In Mandla",
      "Dermatologist In Mandla",
      "Cosmetologist In Mandla"
    ],
    Wardha: [
      "Hair Transplant In Wardha",
      "Hair Transplant Specialist In Wardha",
      "Dermatologist In Wardha"
    ],
    Gondia: [
      "Hair Transplant In Gondia",
      "Hair Transplant Specialist In Gondia",
      "Dermatologist In Gondia"
    ],
    Raipur: [
      "Hair Transplant In Raipur",
      "Hair Transplant Specialist In Raipur",
      "Hair Transplant Clinic In Raipur",
      "Hair Transplant Doctor In Raipur",
      "Top Rated Hair Transplant Specialist In Raipur",
      "Top Rated Hair Transplant Doctor In Raipur",
      "PRP Treatment In Raipur",
      "PRP Therapy In Raipur",
      "Skin Specialist In Raipur",
      "Skin Doctor In Raipur",
      "Skin Clinic In Raipur",
      "Dermatologist In Raipur",
      "Cosmetologist In Raipur"
    ],
    Bilaspur: [
      "Hair Transplant In Bilaspur",
      "Hair Transplant Specialist In Bilaspur",
      "Hair Transplant Clinic In Bilaspur",
      "Hair Transplant Doctor In Bilaspur",
      "Top Rated Hair Transplant Specialist In Bilaspur",
      "Top Rated Hair Transplant Doctor In Bilaspur",
      "PRP Treatment In Bilaspur",
      "PRP Therapy In Bilaspur",
      "Skin Specialist In Bilaspur",
      "Skin Doctor In Bilaspur",
      "Skin Clinic In Bilaspur",
      "Dermatologist In Bilaspur",
      "Cosmetologist In Bilaspur"
    ]
  }
  