import Yogesh_review from '../../assets/Home/Review Hairs/Yogesh_review.mp4'
import Mayur_Karro_Review from '../../assets/Home/Review Hairs/Mayur_Karro_Review.mp4'
import Mustafa from '../../assets/Home/Review Hairs/Mustafa.mp4'

export const TestimonialHomeHair=[

    {
            video:'',
            Treatment:'Hair Transplant',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Scalp Micropigmentation',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'PRP Therapy',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
        video:Yogesh_review ,
        Treatment:'Hair Transplant',
        Name:'Yogesh',
        Position:'Lawyer',
        Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
},
{
        video:Mayur_Karro_Review,
        Treatment:'Scalp Micropigmentation',
        Name:'Mayur Karro',
        Position:'Lawyer',
        Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
},
{
        video:Mustafa,
        Treatment:'PRP Therapy',
        Name:'Mustafa',
        Position:'Lawyer',
        Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
},
    {
            video:'',
            Treatment:'Hair Transplant',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Scalp Micropigmentation',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'PRP Therapy',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
]
export const TestimonialHomeSkin=[
    {
            video:'',
            Treatment:'Chemical Peels',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Thermage',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Acne Blue Light Therapy',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Chemical Peels',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Thermage',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Acne Blue Light Therapy',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Chemical Peels',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Thermage',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Acne Blue Light Therapy',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
]

export const TestimonialHomeLaser=[
    {
            video:'',
            Treatment:'Laser Resurfacing',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Laser Skin Rejuvenation',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Acne Blue Light Therapy',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Laser Resurfacing',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Laser Skin Rejuvenation',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Acne Blue Light Therapy',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Laser Resurfacing',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Laser Skin Rejuvenation',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
    {
            video:'',
            Treatment:'Acne Blue Light Therapy',
            Name:'Deepika Agarwal',
            Position:'Lawyer',
            Review:'Barde Radiance really the best ever in India mostly Face-lift service  is a cosmetic surgical procedure to create a younger appearance in your face. The procedure can reduce the sagging. really the best ever in India mostly  Face-lift',
    },
]