import PRP from "../../assets/Services/PRP.svg";
import ScalpMicropigmentation from "../../assets/Services/ScalpMicropigmentation.svg";

export const Hairtreatments = [
  {
    CardTitle:"Hair Transplant",
    title: "Hair Transplant",
    subtitle: "(Fue & FUT)",
    description:
      "Hair loss is a widespread concern in modern urban life. Over 60% of men and around 10% of women experience some degree of balding, which often leads to a significant loss of self-confidence and affects one’s overall appearance. As a result, hair transplant procedures have become one of the most sought-after cosmetic surgeries today. The good news is that hair transplantation has advanced significantly, providing natural-looking results and near-permanent solutions. Whether you're dealing with mild thinning or advanced baldness, modern minimally invasive techniques can restore a full, youthful hairline with remarkable outcomes. At Radiance, we tailor every hair restoration plan to match the unique needs of each individual, ensuring the best possible results.",
    approach:
      "At Radiance, we understand that no two cases are alike. That’s why we take a personalized approach to each hair transplant procedure, carefully selecting the most suitable method for your specific needs. Our hair transplant technique is minimally invasive, involving the extraction of hair follicles from the donor area (typically the back or sides of the head) and implanting them into the bald or thinning regions. The number of follicles required depends on the extent of baldness. In addition to traditional hair transplants, we incorporate several next-gen solutions based on your hair loss pattern and condition, ensuring a seamless, natural look that enhances your appearance and restores confidence.",
    Diagnose:
      "Our experts perform a detailed analysis of your scalp and hair condition, identifying the underlying cause of your hair loss to ensure accurate diagnosis and effective treatment planning",
      Treat:"A customized treatment plan is developed for you, utilizing advanced technology and techniques tailored to your individual diagnosis. Our goal is to provide the best possible outcome for your hair restoration journey.",
      Maintain:"Ongoing monitoring ensures that your treatment progresses smoothly. We provide expert guidance on diet, medications, and hair care, helping you maintain your new hair growth and achieve long-term success.",
      AfterCare:[
      "<strong >Post-Procedure Consultation: </strong>Personalized follow-up sessions to monitor healing and progress.",
      "<strong >Specialized Hair Wash Service: </strong>Professional washing of the treated area for the first few sessions.",
      "<strong >Medication Guidance: </strong> Assistance with post-procedure medications and their usage.",
      "<strong >Scalp Care Kits: </strong> Provide specially formulated shampoos, lotions, and aftercare products.</strong>",
      "<strong>24/7 Support Line: </strong> Access to a helpline for any urgent questions or concerns.</strong>",
    ],
      image: PRP,
  },
  {
    CardTitle:"FUE",
    title: "FUE",
    subtitle: "Hair Transplant",
    description: "FUE (Follicular Unit Extraction) is a popular hair transplant technique that involves extracting hair follicles one by one from the donor area. Unlike the traditional FUT (Follicular Unit Transplant), FUE leaves no linear scars and offers a quicker recovery time. This technique is ideal for restoring hair on the scalp, eyebrows, beard, and moustache. FUE provides natural-looking results and is minimally invasive, making it a preferred option for many patients. The procedure requires a skilled surgeon, and at Radiance Clinic, we ensure high-quality care and expertise",
    approach: "At Radiance Clinic, we specialize in FUE hair transplants, ensuring a precise and effective procedure. The hair follicles are extracted using tiny circular incisions, leaving minimal marks that heal quickly. There’s no need for stitches, and the donor area remains scar-free. Our certified surgeons perform the procedure with the latest technology, delivering natural results tailored to your unique needs",
    Diagnose:"We assess your scalp and hair condition to identify the cause of hair loss and develop a personalized treatment plan.",
    Treat:"Using advanced FUE techniques, we perform the hair transplant with precision, ensuring optimal results.",
    Maintain:"We monitor your progress and provide guidance on diet, medications, and hair care to support long-term results.",
    AfterCare:[
      "<strong>Post-Procedure Consultation: </strong>Follow-up sessions to monitor healing.",
      "<strong>Specialized Hair Wash Service: </strong> Professional washing of the treated area.",
      "<strong>Medication Guidance: </strong> Assistance with post-procedure medications.",
      "<strong>Scalp Care Kits: </strong> Formulated products for hair care and healing.</strong>",
      "<strong>24/7 Support Line: </strong> Access to a helpline for any concerns.</strong>",
    ],
    image: ScalpMicropigmentation,
  },
  {
    CardTitle:"Female Hair Transplant",
    title: "Female",
    subtitle: "Hair Transplant",
    description:"While female hair loss is less common than in men, it can be just as devastating for those affected. Unlike male pattern baldness, which follows a horseshoe shape, female hair thinning typically begins at the crown and spreads across the scalp. Women face unique challenges like pregnancy, hormonal imbalances, stress, and dieting, all of which can contribute to hair loss. As a result, female hair transplant techniques must be specifically tailored to address these factors. At Radiance Clinic, we offer specialized solutions for female hair restoration, ensuring natural, lasting results that restore both your hair and your confidence.",
    approach:"At Radiance Clinic, the process of female hair transplant begins with a thorough examination of your baldness pattern and medical history. Understanding the root cause of your hair loss is crucial to determining whether you are a suitable candidate for a transplant. For female pattern baldness, hair follicles are extracted from unaffected donor areas and transplanted to the thinning regions. Unlike men, women’s donor areas can also be prone to thinning, so careful selection of follicles from stable sites is essential for success. Our team of experts ensures that the procedure is performed with precision, using the latest techniques to achieve the best possible outcome.",
    Diagnose:"We conduct a comprehensive assessment of your hair and scalp condition, determining the underlying cause of your hair loss.",
    Treat:"Based on the diagnosis, we create a customized treatment plan, utilizing advanced techniques to restore your hair.",
    Maintain:"We provide ongoing monitoring and offer guidance on diet, medications, and hair care to ensure long-term success.",
    AfterCare:[
      "<strong>Post-Procedure Consultation: </strong>Follow-up sessions to monitor healing.",
      "<strong>Specialized Hair Wash Service: </strong> Professional washing of the treated area.",
      "<strong>Medication Guidance: </strong> Assistance with post-procedure medications.",
      "<strong>Scalp Care Kits: </strong> Formulated products for hair care and healing.</strong>",
      "<strong>24/7 Support Line: </strong> Access to a helpline for any concerns.</strong>",
    ],
    image: PRP,
  },
  {
    CardTitle:"PRP Therapy",
    title: "PRP Therapy",
    subtitle: "Non-Surgical Hair Restoration",
    description:"Platelet Rich Plasma (PRP) therapy is a revolutionary, non-surgical treatment for hair loss and thinning. By utilizing the patient’s own blood, PRP delivers growth factors to rejuvenate hair follicles and promote natural regrowth. This safe, minimally invasive procedure is ideal for those in the early stages of hair loss, providing visible results and restoring confidence.",
    approach:"At Radiance Clinic, our PRP therapy begins with a thorough scalp analysis to ensure suitability. Our specialists design a personalized treatment plan tailored to your needs. The process includes extracting a small amount of blood, isolating the platelet-rich plasma, and injecting it into the scalp to activate dormant follicles. Each session is quick, taking less than 30 minutes, and is performed with precision to ensure the best outcomes.",
    Diagnose:"Comprehensive trichoscopy to analyze scalp and hair health.",
    Treat:"Customized PRP injections to stimulate hair follicles using advanced techniques.",
    Maintain:"Continuous monitoring and expert guidance on diet, medications, and hair care to enhance and sustain results.",
    AfterCare:[
      "<strong>Post-Procedure Consultation: </strong>Follow-up sessions to monitor healing.",
      "<strong>Specialized Hair Wash Service: </strong> Professional washing of the treated area.",
      "<strong>Medication Guidance: </strong> Assistance with post-procedure medications.",
      "<strong>Scalp Care Kits: </strong> Formulated products for hair care and healing.</strong>",
      "<strong>24/7 Support Line: </strong> Access to a helpline for any concerns.</strong>",
    ],
    image: PRP,
  },
  {
    CardTitle:"Eyebrow & Beard Hair Transplant",
    title: "Eyebrow & Beard",
    subtitle: "Hair Transplant",
    description:"Struggling with patchy beards or uneven eyebrows? Nearly 50% of men face challenges in growing a full, even beard, while many others deal with sparse or uneven eyebrows. Facial hair transplants, using the advanced Follicular Unit Extraction (FUE) technique, offer a minimally invasive solution with natural results. This method effectively restores facial hair in targeted areas, ensuring a fuller, well-defined look without noticeable scarring.",
    approach:"At Radiance Clinic, we specialize in facial hair transplants using the FUE technique. This involves carefully extracting individual hair follicles and implanting them into the beard or eyebrow area with precision. Our experienced surgeons assess the hair and skin condition, determine the number of grafts needed, and design a personalized plan to ensure natural, seamless results. With a high success rate and minimally invasive procedures, Radiance ensures safe and effective facial hair restoration.",
    Diagnose:"Detailed assessment of facial hair density and skin condition to identify the root cause.",
    Treat:"Develop a customized plan and perform precise FUE transplants for natural-looking results.",
    Maintain:"Continuous monitoring, along with expert advice on aftercare, diet, and medications for lasting outcomes.",
    AfterCare:[
      "<strong>Post-Procedure Consultation: </strong>Follow-up sessions to monitor healing.",
      "<strong>Specialized Hair Wash Service: </strong> Professional washing of the treated area.",
      "<strong>Medication Guidance: </strong> Assistance with post-procedure medications.",
      "<strong>Scalp Care Kits: </strong> Formulated products for hair care and healing.</strong>",
      "<strong>24/7 Support Line: </strong> Access to a helpline for any concerns.</strong>",
    ],
    image: ScalpMicropigmentation,
  },
  {
    CardTitle:"Alopecia Treatment",
    title: "Comprehensive",
    subtitle: "Alopecia Treatment",
    description:"Alopecia refers to various hair loss conditions, each with unique causes and treatments. From patchy hair loss (Alopecia Areata) to complete baldness (Alopecia Totalis), and conditions like Traction Alopecia, Telogen Effluvium, or Anagen Effluvium, the treatment depends on the underlying cause. Solutions may include medications, Platelet Rich Plasma (PRP) therapy, or advanced hair transplant techniques, tailored to individual needs for optimal results.",
    approach:"At Radiance Clinic, we specialize in diagnosing and treating all types of alopecia. Our experts conduct a thorough analysis to identify the root cause and recommend the most effective solution, from topical and oral medications to cutting-edge procedures like PRP or hair transplants. Our team stays updated with the latest advancements, ensuring every patient receives the best care. Post-treatment monitoring and personalized aftercare are integral to our approach, helping patients achieve lasting results.",
    Diagnose:"Detailed analysis of hair and scalp conditions to determine the type and cause of alopecia.",
    Treat:"Develop and execute a customized treatment plan using advanced technologies and techniques like PRP or hair transplants.",
    Maintain:"Ongoing monitoring, personalized care plans, and guidance on diet, medications, and hair care for sustained results.",
    AfterCare:[
      "<strong>Post-Procedure Consultation: </strong>Follow-up sessions to monitor healing.",
      "<strong>Specialized Hair Wash Service: </strong> Professional washing of the treated area.",
      "<strong>Medication Guidance: </strong> Assistance with post-procedure medications.",
      "<strong>Scalp Care Kits: </strong> Formulated products for hair care and healing.</strong>",
      "<strong>24/7 Support Line: </strong> Access to a helpline for any concerns.</strong>",
    ],
    image: PRP,
  },
  // {
  //   CardTitlw:"Alopecia Treatment",
  //   title: "Expert Hair",
  //   subtitle: "Transplant Repair",
  //   description:"Hair transplants can transform lives, but rushing into treatment without proper research can lead to unsatisfactory results. Poorly executed procedures can affect your appearance and peace of mind. At Radiance Clinic, we specialize in repairing and refining hair transplants to restore natural-looking, healthy hair. With expert care and advanced techniques, we help patients regain confidence and achieve the results they deserve.",
  //   approach:"Radiance Clinic is renowned for its expertise in hair transplant repair. Each case begins with a thorough assessment of the scalp, hair condition, and patient history to identify the root cause of the issue. Our experts provide clear guidance on available options, fair pricing, and the expected outcomes. Using advanced techniques, we focus on achieving natural results while ensuring patient safety and satisfaction.",
  //   Diagnose:"Comprehensive evaluation of hair and scalp condition to determine the problem and its cause.",
  //   Treat:"Develop a personalized repair plan using state-of-the-art techniques tailored to each patient’s needs.",
  //   Maintain:"Ongoing support with regular monitoring, guidance on post-procedure care, and advice on hair health maintenance.",
  //   AfterCare:[
  //     "<strong>Post-Procedure Consultation: </strong>Follow-up sessions to monitor healing.",
  //     "<strong>Specialized Hair Wash Service: </strong> Professional washing of the treated area.",
  //     "<strong>Medication Guidance: </strong> Assistance with post-procedure medications.",
  //     "<strong>Scalp Care Kits: </strong> Formulated products for hair care and healing.</strong>",
  //     "<strong>24/7 Support Line: </strong> Access to a helpline for any concerns.</strong>",
  //   ],
  //   image: PRP,
  // },
];

export const Skintreatments = [
  {
    CardTitle:"Pimple Treatment",
    title: "Pimple Treatment",
    //   subtitle: '(Fue & FUT)',
    description:"Acne, or pimples, is a common skin issue affecting both men and women, especially during adolescence due to hormonal changes. However, acne can persist at any age, particularly in individuals with oily skin. Blocked sebaceous glands lead to pimples, blackheads, whiteheads, and other types of acne. Treatment varies from medications and hormone therapy to skin treatments like laser therapy, depending on the type of acne.",
   approach:"At Radiance Clinic, we understand how acne can affect your confidence and well-being. Our approach starts with diagnosing the type and root cause of acne, followed by a personalized treatment plan. We combine oral and topical medications, hormonal therapy, and advanced treatments like chemical peels, skin polishing, laser treatments, and blue light therapy. Using state-of-the-art technology, we ensure safe and effective results for acne management and prevention.",
     Diagnose:"Comprehensive skin analysis to identify the type and cause of acne.",
    Treat:"Customized treatment plans, including medications and advanced therapies, based on expert diagnosis.",
    Maintain:"Continuous monitoring and advice on diet, medications, and skincare for optimal results.",
   AfterCare:[
      "<strong>Post-Procedure Consultation: </strong>Follow-up sessions to monitor healing.",
      "<strong>Specialized Hair Wash Service: </strong> Professional washing of the treated area.",
     "<strong>Medication Guidance: </strong> Assistance with post-procedure medications.",
     "<strong>Scalp Care Kits: </strong> Formulated products for hair care and healing.</strong>",
     "<strong>24/7 Support Line: </strong> Access to a helpline for any concerns.</strong>",
   ],
    image: PRP,
  },
  {
    CardTitle:"Acne Scar Treatment",
    title: "Pimple/",
    subtitle: "Acne Scar Treatment",
    description:"Acne scars can significantly affect one’s appearance, leading to insecurity and reduced confidence. These scars often appear on the face, back, neck, and shoulders, and can be difficult to treat. Treatments for acne scars include topical creams, cryotherapy, steroid injections, chemical peels, and advanced laser therapies. Radiance Clinic offers cutting-edge solutions to minimize the appearance of acne scars and restore smooth, clear skin.",
    approach:"At Radiance Clinic, we specialize in advanced acne scar treatments tailored to your skin type. Our experts carefully select treatments that target the scars without affecting the surrounding skin. We offer a range of therapies, including steroid injections, cryotherapy, blue light therapy, IPL laser, chemical peels, and our unique Cocktail Management treatment. These procedures deliver visible results with minimal side effects, helping you regain your confidence.",
      Diagnose:"Comprehensive skin analysis to determine the type and severity of acne scars.",
     Treat:"Customized treatment plan using advanced technologies like laser therapy, cryotherapy, and more.",
     Maintain:"Ongoing monitoring and guidance on skincare, diet, and medications for optimal results.",
    AfterCare:[
       "<strong>Post-Procedure Consultation: </strong>Follow-up sessions to monitor healing.",
       "<strong>Specialized Hair Wash Service: </strong> Professional washing of the treated area.",
      "<strong>Medication Guidance: </strong> Assistance with post-procedure medications.",
      "<strong>Scalp Care Kits: </strong> Formulated products for hair care and healing.</strong>",
      "<strong>24/7 Support Line: </strong> Access to a helpline for any concerns.</strong>",
    ],
    image: ScalpMicropigmentation,
  },
  {
    CardTitle:"Rejuvenation of Skin",
    title: "Skin Rejuvenation",
      subtitle: 'Treatment',
    description:"Skin is the most visible organ, and it’s often affected by stress, pollution, and environmental factors like sunlight and harsh weather. These elements accelerate aging, leading to brown spots, fine lines, wrinkles, and sagging. Skin rejuvenation treatments aim to restore youthful skin, improve complexion, and reduce visible signs of aging. Popular treatments like Intense Pulsed Light (IPL) and chemical peels are highly effective in restoring skin’s vitality.",
    approach:"At Radiance Clinic, we offer advanced skin rejuvenation therapies for age reversal and skin revitalization. Our experts specialize in IPL, a light-based treatment that targets age spots, wrinkles, and broken blood vessels, as well as chemical peels using glycolic or lactic acid to enhance skin texture. Each treatment is personalized to meet your skin’s needs, and we provide detailed aftercare instructions to ensure the best results, including sun protection and a skincare routine.",
      Diagnose:"Thorough skin analysis to assess damage and identify the best treatment options.",
     Treat:"Customized rejuvenation plan using IPL, chemical peels, or other advanced techniques",
     Maintain:"Ongoing monitoring and guidance on skincare, diet, and post-treatment care for optimal results.",
    AfterCare:[
       "<strong>Post-Procedure Consultation: </strong>Follow-up sessions to monitor healing.",
       "<strong>Specialized Hair Wash Service: </strong> Professional washing of the treated area.",
      "<strong>Medication Guidance: </strong> Assistance with post-procedure medications.",
      "<strong>Scalp Care Kits: </strong> Formulated products for hair care and healing.</strong>",
      "<strong>24/7 Support Line: </strong> Access to a helpline for any concerns.</strong>",
    ],
    image: PRP,
  },
  {
    CardTitle:"Chemical Peels",
    title: "Chemical Peels",
    //   subtitle: 'Plasma Therapy',
    description:"Chemical peels are an effective skin treatment that enhances texture and appearance by targeting sun damage, pigmentation, and superficial scars. This procedure involves applying chemical solutions like glycolic acid, salicylic acid, or trichloroacetic acid to exfoliate the skin's top layer, allowing fresh, healthy skin to regenerate. Chemical peels are a safe and highly effective treatment when performed by trained professionals, as the process requires precision and care.",
    approach:"At Radiance Clinic, our experts are highly skilled in performing chemical peels with the latest solutions and techniques. After a thorough skin assessment, we customize the treatment based on the depth required for optimal results. While the procedure involves temporary redness, scaling, and blistering, the healing process typically takes 7-10 days. Our specialists ensure proper aftercare, including skin protection and guidance on maintaining results.",
      Diagnose:"Detailed skin analysis to determine the appropriate type and depth of the peel",
     Treat:"Customized chemical peel treatment using advanced solutions tailored to your skin’s needs.",
     Maintain:"Ongoing care and monitoring to ensure healing and long-term results, with expert guidance on skincare and diet.",
    AfterCare:[
       "<strong>Post-Procedure Consultation: </strong>Follow-up sessions to monitor healing.",
       "<strong>Specialized Hair Wash Service: </strong> Professional washing of the treated area.",
      "<strong>Medication Guidance: </strong> Assistance with post-procedure medications.",
      "<strong>Scalp Care Kits: </strong> Formulated products for hair care and healing.</strong>",
      "<strong>24/7 Support Line: </strong> Access to a helpline for any concerns.</strong>",
    ],
    image: PRP,
  },
  {
    CardTitle:"Meso Glow Treatment",
    title: "Meso Glow",
    subtitle: 'Treatment',
    description:"Meso Glow, also known as Mesoface or cosmetic mesotherapy, is a skin rejuvenation technique that infuses the skin with vitamins, antioxidants, and other nutrients to restore a youthful glow. This treatment involves fine needle injections of customized ingredients like Vitamin C, glutathione, and amino acids, which target skin brightening, rejuvenation, and tightening. The effects of Meso Glow typically last for 3-4 months, leaving the skin fresh, taut, and radiant.",
    approach:"At Radiance Clinic, we offer Meso Glow treatments tailored to your specific skin needs, including brightening, rejuvenation, and tightening. Brightening treatments use glutathione and Vitamin C for a lighter, glowing complexion. Rejuvenation mesotherapy combines vitamins and amino acids to restore soft, supple skin. For anti-aging and skin tightening, we use collagen injections and fillers to firm sagging skin and replenish essential nutrients like hyaluronic acid and collagen.ion and guidance on maintaining results.",
      Diagnose:"Detailed skin analysis to understand the unique needs of your skin.",
     Treat:"Customized mesotherapy injections based on your skin’s requirements (brightening, rejuvenation, or tightening).",
     Maintain:"Ongoing monitoring and expert guidance on skincare, diet, and post-treatment care to ensure lasting results.",
    AfterCare:[
       "<strong>Post-Procedure Consultation: </strong>Follow-up sessions to monitor healing.",
       "<strong>Specialized Hair Wash Service: </strong> Professional washing of the treated area.",
      "<strong>Medication Guidance: </strong> Assistance with post-procedure medications.",
      "<strong>Scalp Care Kits: </strong> Formulated products for hair care and healing.</strong>",
      "<strong>24/7 Support Line: </strong> Access to a helpline for any concerns.</strong>",
    ],
    image: ScalpMicropigmentation,
  },
  {
    CardTitle:"Pigment Reduction",
    title: "Pigment Reduction",
    //   subtitle: 'Repair',
    description:"Pigmentation issues, whether from sun damage or skin conditions, affect many people across different skin tones. Light-skinned individuals often struggle with dark spots from sun exposure, while darker skin tones are more prone to melasma (patchy brown discoloration) and post-inflammatory hyperpigmentation (PIH). Pigment reduction treatments vary based on the type of pigmentation and may involve a combination of therapies such as topical treatments, chemical peels, light therapy, and laser treatments.",
    approach:"At Radiance Clinic, we understand that pigmentation concerns are unique to each individual. Our expert team tailors treatments to target your specific skin condition, whether it's sun-induced dark spots or melasma. For light-skinned individuals, we often use topical treatments like hydroquinone or retinol, combined with chemical peels containing glycolic or salicylic acid. For deeper pigmentation, we apply advanced treatments like Intense Pulsed Light (IPL) and Q-switched lasers. With a customized approach, we ensure the most effective results for every patient.",
      Diagnose:"We start by thoroughly examining your skin to understand the root cause of pigmentation and identify the most suitable treatment for you.",
     Treat:"Based on your skin’s needs, we create a personalized treatment plan that may include topical therapies, chemical peels, or laser treatments like IPL and Q-switched lasers.",
     Maintain:"We provide continuous monitoring and expert guidance on diet, skincare, and post-treatment care to maintain your results and keep your skin glowing.",
    AfterCare:[
       "<strong>Post-Procedure Consultation: </strong>Follow-up sessions to monitor healing.",
       "<strong>Specialized Hair Wash Service: </strong> Professional washing of the treated area.",
      "<strong>Medication Guidance: </strong> Assistance with post-procedure medications.",
      "<strong>Scalp Care Kits: </strong> Formulated products for hair care and healing.</strong>",
      "<strong>24/7 Support Line: </strong> Access to a helpline for any concerns.</strong>",
    ],
    image: PRP,
  },
  {
    CardTitle:"Microdermabrasion",
    title: "Microdermabrasion",
    subtitle: "(Skin Polishing)",
    description:"Microdermabrasion is a popular, non-invasive treatment that works wonders for skin rejuvenation. Whether you're dealing with scars, discoloration, stretch marks, or sun damage, microdermabrasion can help restore your skin’s smoothness and clarity. This treatment involves gently exfoliating the outer layer of your skin using a fine abrasive technique, which stimulates the production of new skin cells and collagen. The result? A smoother, tighter, and more youthful-looking complexion.",
    approach:"At Radiance Clinic, we offer advanced microdermabrasion treatments using the latest equipment and techniques. Our expert professionals use microcrystals (such as aluminum oxide or sodium chloride) to gently exfoliate the skin’s surface. This process helps reduce hyperpigmentation, age spots, fine lines, wrinkles, and stretch marks. We also target acne scars, enlarged pores, and uneven complexion, leaving you with fresher, more vibrant skin.",
      Diagnose:"Our experts begin by carefully examining your skin to identify the specific concerns that need attention.",
     Treat:"Based on your diagnosis, we create a customized microdermabrasion treatment plan, using advanced technology to target your skin’s needs.",
     Maintain:"After the treatment, we guide you on maintaining your results with the right skincare routine, diet, and medications to keep your skin looking radiant.",
    AfterCare:[
       "<strong>Post-Procedure Consultation: </strong>Follow-up sessions to monitor healing.",
       "<strong>Specialized Hair Wash Service: </strong> Professional washing of the treated area.",
      "<strong>Medication Guidance: </strong> Assistance with post-procedure medications.",
      "<strong>Scalp Care Kits: </strong> Formulated products for hair care and healing.</strong>",
      "<strong>24/7 Support Line: </strong> Access to a helpline for any concerns.</strong>",
    ],
    image: PRP,
  },
];
